import numpy as np

Borg=np.loadtxt('./Attainment/Borg_attainment_epsilon.txt')
MOEAD=np.loadtxt('./Attainment/MOEAD_attainment_epsilon.txt')
NSGAII=np.loadtxt('./Attainment/NSGAII_attainment_epsilon.txt')
NSGAIII=np.loadtxt('./Attainment/NSGAIII_attainment_epsilon.txt')
RVEA=np.loadtxt('./Attainment/RVEA_attainment_epsilon.txt')
#C=np.loadtxt('./hv_files50MC/attainment_vectors/attain_hv_50MC_1I_128P.txt')
#D=np.loadtxt('./hv_files50MC/attainment_vectors/attain_hv_50MC_1I_256P.txt')
#E=np.loadtxt('./hv_files50MC/attainment_vectors/attain_hv_50MC_2I_32P.txt')
#F=np.loadtxt('./hv_files50MC/attainment_vectors/attain_hv_50MC_2I_64P.txt')
#G=np.loadtxt('./hv_files50MC/attainment_vectors/attain_hv_50MC_2I_128P.txt')
#H=np.loadtxt('./hv_files50MC/attainment_vectors/attain_hv_50MC_2I_256P.txt')
#I=np.loadtxt('./hv_files50MC/attainment_vectors/attain_hv_50MC_4I_32P.txt')
#J=np.loadtxt('./hv_files50MC/attainment_vectors/attain_hv_50MC_4I_64P.txt')
#K=np.loadtxt('./hv_files50MC/attainment_vectors/attain_hv_50MC_4I_128P.txt')
#L=np.loadtxt('./hv_files50MC/attainment_vectors/attain_hv_50MC_4I_256P.txt')
#M=np.loadtxt('./hv_files50MC/attainment_vectors/attain_hv_50MC_8I_64P.txt')
#N=np.loadtxt('./hv_files50MC/attainment_vectors/attain_hv_50MC_8I_128P.txt')
#O=np.loadtxt('./hv_files50MC/attainment_vectors/attain_hv_50MC_8I_256P.txt')
#P=np.loadtxt('./hv_files50MC/attainment_vectors/attain_hv_50MC_16I_128P.txt')
#Q=np.loadtxt('./hv_files50MC/attainment_vectors/attain_hv_50MC_16I_256P.txt')
#1000MC
#ms32=np.loadtxt('./hv_files/attainment_vectors/attain_hv_1000MC_1I_32P.txt')
#ms64=np.loadtxt('./hv_files/attainment_vectors/attain_hv_1000MC_1I_64P.txt')
#ms128=np.loadtxt('./hv_files/attainment_vectors/attain_hv_1000MC_1I_128P.txt')
#ms256=np.loadtxt('./hv_files/attainment_vectors/attain_hv_1000MC_1I_256P.txt')
#A=np.loadtxt('./hv_files/attainment_vectors/attain_hv_1000MC_2I_32P.txt')
#B=np.loadtxt('./hv_files/attainment_vectors/attain_hv_1000MC_2I_64P.txt')
#C=np.loadtxt('./hv_files/attainment_vectors/attain_hv_1000MC_2I_128P.txt')
#D=np.loadtxt('./hv_files/attainment_vectors/attain_hv_1000MC_2I_256P.txt')
#E=np.loadtxt('./hv_files/attainment_vectors/attain_hv_1000MC_4I_32P.txt')
#F=np.loadtxt('./hv_files/attainment_vectors/attain_hv_1000MC_4I_64P.txt')
#G=np.loadtxt('./hv_files/attainment_vectors/attain_hv_1000MC_4I_128P.txt')
#H=np.loadtxt('./hv_files/attainment_vectors/attain_hv_1000MC_4I_256P.txt')
#I=np.loadtxt('./hv_files/attainment_vectors/attain_hv_1000MC_8I_64P.txt')
#J=np.loadtxt('./hv_files/attainment_vectors/attain_hv_1000MC_8I_128P.txt')
#K=np.loadtxt('./hv_files/attainment_vectors/attain_hv_1000MC_8I_256P.txt')
#L=np.loadtxt('./hv_files/attainment_vectors/attain_hv_1000MC_16I_128P.txt')
#M=np.loadtxt('./hv_files/attainment_vectors/attain_hv_1000MC_16I_256P.txt')


# ms32=np.loadtxt('./hv_files500MC/attainment_vectors/attain_hv_500MC_1I_32P.txt')
# ms64=np.loadtxt('./hv_files500MC/attainment_vectors/attain_hv_500MC_1I_64P.txt')
# ms128=np.loadtxt('./hv_files500MC/attainment_vectors/attain_hv_500MC_1I_128P.txt')
# ms256=np.loadtxt('./hv_files500MC/attainment_vectors/attain_hv_500MC_1I_256P.txt')
# A=np.loadtxt('./hv_files500MC/attainment_vectors/attain_hv_500MC_2I_32P.txt')
# B=np.loadtxt('./hv_files500MC/attainment_vectors/attain_hv_500MC_2I_64P.txt')
# C=np.loadtxt('./hv_files500MC/attainment_vectors/attain_hv_500MC_2I_128P.txt')
# D=np.loadtxt('./hv_files500MC/attainment_vectors/attain_hv_500MC_2I_256P.txt')
# E=np.loadtxt('./hv_files500MC/attainment_vectors/attain_hv_500MC_4I_32P.txt')
# F=np.loadtxt('./hv_files500MC/attainment_vectors/attain_hv_500MC_4I_64P.txt')
# G=np.loadtxt('./hv_files500MC/attainment_vectors/attain_hv_500MC_4I_128P.txt')
# H=np.loadtxt('./hv_files500MC/attainment_vectors/attain_hv_500MC_4I_256P.txt')
# I=np.loadtxt('./hv_files500MC/attainment_vectors/attain_hv_500MC_8I_64P.txt')
# J=np.loadtxt('./hv_files500MC/attainment_vectors/attain_hv_500MC_8I_128P.txt')
# K=np.loadtxt('./hv_files500MC/attainment_vectors/attain_hv_500MC_8I_256P.txt')
# L=np.loadtxt('./hv_files500MC/attainment_vectors/attain_hv_500MC_16I_128P.txt')
# M=np.loadtxt('./hv_files500MC/attainment_vectors/attain_hv_500MC_16I_256P.txt')



#best_of_best=  0.521664697169
#configurations=[A.T,B.T,C.T,D.T,E.T,F.T,G.T,H.T,I.T,J.T,K.T,L.T,M.T]
#configurations=(A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q)
configurations=(Borg, MOEAD, NSGAII, NSGAIII,RVEA)
#configurations=(I,H,M,F,A,C,E,G,B,J,K,L,D,N,O,P,Q)
#configurations=(B,D,H,F,C,A,E,G,I,J,K,L,M,N,O,P,Q)
configurations=np.array(configurations)
configurations=configurations.T
#print np.size(configurations,1)

np.savetxt('./Attainment/attainment_vectors.txt', configurations)